version: 0.2
phases:
  pre_build:
    commands:
      - npm install 

  build:
    commands:
      - npm build
  pre_build:
    commands:

  artifacts:
    files:
      - '**/*'
    discard-paths: no
    base-directory: build
